=== egeorge830/xml_xsd_validation/exercise_1/data/library.dtd
<!ELEMENT library (book*)>              <!-- Zero or more book elements -->
<!ELEMENT book (title, author+, year?)> <!-- One or more authors, year optional -->
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== egeorge830/xml_xsd_validation/exercise_1/data/library.xml
<?xml version="1.0"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
    <book>
        <title>1984</title>
        <author>George Orwell</author>
        <year>1949</year>
    </book>
    <book>
        <title>Good Omens</title>
        <author>Neil Gaiman</author>
        <author>Terry Pratchett</author>
    </book>
</library>
